import { Project, Tags, TechStack } from "../interfaces";
import { AccentColours } from "../../theme";

const projects: Project[] = [
  {
    title: "Ted Baker",
    tag: Tags.job,
    date: "June 2021 - current",
    text: "A composable modern eCommerce website, made on a multi-storefront Bloomreach headless CMS. Next.js-built integrated SPA.",
    stack: [
      TechStack.TypeScript,
      TechStack.Next,
      TechStack.Jest,
      TechStack.a11y,
      TechStack.styled,
    ],
    color: AccentColours.teal,
    link: "https://www.tedbaker.com/",
  },
  {
    title: "Spotify Releaser",
    tag: Tags.pet,
    date: "July 2022 - current",
    text: "Never miss new releases! Spotify API integrated app to track new music from your favourite artists. Built with Remix.run. Please reach out to get a full access!",
    stack: [
      TechStack.TypeScript,
      TechStack.Remix,
      TechStack.a11y,
      TechStack.styled,
    ],
    color: AccentColours.lightgreen,
    link: "https://spotify-releaser.vercel.app/",
    github: "https://github.com/lazy-ocean/releaser",
  },
  {
    title: "The Pushkin State Museum - a11y playground",
    tag: Tags.learning,
    date: "March - May 2022",
    text: "An a11y showcase website. Tested with VoiceOver, axe, w3c HTML validator, Wave, keyboard-friendly, WCAG 2.0 compliant colors, 4x 100% Lighthouse index.",
    stack: [
      TechStack.a11y,
      TechStack.TypeScript,
      TechStack.Next,
      TechStack.styled,
    ],
    color: AccentColours.violet,
    link: "https://a11y-showcase-museum.vercel.app/en",
    github: "https://github.com/lazy-ocean/a11y-showcase-museum",
  },
  {
    title: "App boilerplate",
    tag: Tags.pet,
    date: "January 2022 - current",
    text: "A Next.js boilerplate to create SSRd apps without breaking a sweat. Made with testing (Jest), lintering (eslint + Prettier) and conventional commits (Husky) in mind.",
    stack: [TechStack.TypeScript, TechStack.Next, TechStack.Jest],
    color: AccentColours.pink,
    link: "https://github.com/lazy-ocean/next-js-boilerplate",
    github: "https://github.com/lazy-ocean/next-js-boilerplate",
  },
  {
    title: "Spoonacular App",
    tag: Tags.learning,
    date: "May 2021",
    text: "An interview assignment, a Next.js app integrated with Spoonacular API, optimized with caching. Tested with Cypress (end-to-end).",
    stack: [TechStack.TypeScript, TechStack.Next, TechStack.cypress],
    color: AccentColours.yellow,
    link: "https://spoonacular-app.vercel.app/",
    github: "https://github.com/lazy-ocean/spoonacular-app",
  },
  {
    title: "Just Do It app",
    tag: Tags.pet,
    date: "March - May 2021",
    text: "A basic fullstack todo app with user authentication. Built as a tryout of using Express for backend.",
    stack: [TechStack.JavaScript, TechStack.react, TechStack.express],
    color: AccentColours.green,
    link: "https://justdoltapp.herokuapp.com/",
    github: "https://github.com/lazy-ocean/just-do-it-app",
  },
  {
    title: "Coding challenges",
    tag: Tags.learning,
    date: "October 2020 - current",
    text: "A simple set-up to crack code challenges, executing in your code editor and testing as you go + my cracked challenges from Advent of Code, LeetCode, Codewars, etc.",
    stack: [
      TechStack.TypeScript,
      TechStack.JavaScript,
      TechStack.Jest,
      TechStack.npm,
    ],
    color: AccentColours.blue,
    link: "https://github.com/lazy-ocean/coding_challenges",
    github: "https://github.com/lazy-ocean/coding_challenges",
  },
  {
    title: "ROI calculation form (RU) - Inspair",
    tag: Tags.freelance,
    date: "July 2020",
    text: "An interactive form to calculate project ROI and generate annual cash flow table, designed and developed for robotics system integrator Inspair.",
    stack: [TechStack.JavaScript, TechStack.npm, TechStack.gulp],
    color: AccentColours.orange,
    link: "https://inspair.ru/calc",
    github: "https://github.com/lazy-ocean/inspair-calculations-table",
  },
];

export default projects;
